POST http://localhost:8080/export
Content-Type: application/json

{
  "datasetIdentifier": {
    "parentUri": "gs://ssb-rawdata-dev/export",
    "path": "fastsatt-2019",
    "version": "v1"
  },
  "columnSelectors": [
    "**/kontonummer",
    "**/bankensNavn"
  ],
  "pseudoConfig": {
    "rules": [
      {
        "name": "kontonummer",
        "pattern": "**/kontonummer",
        "func": "fpe-anychar(secret1)"
      }
    ]
  },
  "compression": {
    "type": "application/zip",
    "encryption": "AES",
    "password": "kensentme"
  },
  "targetUri": "gs://ssb-rawdata-dev/export/fastsatt-2019.zip",
  "targetContentType": "application/json"
}
