
steps:
  - name: 'gcr.io/cloud-builders/mvn'
    entrypoint: 'mvn'
    args: ['package','-Dmaven.test.skip=true', '-P ssb-bip']

  # Pull jar-file from Artifact Registry instead of building from source.
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - "-c"
      - |
          mkdir -p target/classes
          cp src/main/resources/logback.xml target/classes/.
          curl --oauth2-bearer "$(gcloud auth print-access-token)" -o target/dapla-dlp-pseudo-service-2.1.1-SNAPSHOT.jar \
          -L https://europe-north1-docker.pkg.dev/artifact-registry-14da/maven-snapshots/no.ssb.dlp.pseudo.service/dapla-dlp-pseudo-service-2.1.1-SNAPSHOT.jar

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'europe-north1-docker.pkg.dev/artifact-registry-14da/ssb-docker/ssb/statistikktjenester/automation/dapla-dlp-pseudo', 
           '.']
    
  # Push Docker image to the ssb-docker Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'europe-north1-docker.pkg.dev/artifact-registry-14da/ssb-docker/ssb/statistikktjenester/automation/dapla-dlp-pseudo']

options:
  logging: CLOUD_LOGGING_ONLY
