
steps:

  - name: 'gcr.io/cloud-builders/mvn'
    entrypoint: mvn
    args: ['test']

  - name: 'gcr.io/cloud-builders/mvn'
    entrypoint: mvn
    args: ['package','-Dmaven.test.skip=true']

  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'europe-north1-docker.pkg.dev/artifact-registry-14da/ssb-docker/ssb/statistikktjenester/automation/dapla-dlp-pseudo', 
           '.']
    
  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'europe-north1-docker.pkg.dev/artifact-registry-14da/ssb-docker/ssb/statistikktjenester/automation/dapla-dlp-pseudo']

options:
  logging: CLOUD_LOGGING_ONLY
