
steps:

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - "-c"
      - |
          curl --oauth2-bearer "$(gcloud auth print-access-token)" -o dapla-dlp-pseudo-service-2.1.1-SNAPSHOT.jar \
          -L https://europe-north1-docker.pkg.dev/artifact-registry-14da/maven-snapshots/no.ssb.dlp.pseudo.service/dapla-dlp-pseudo-service-2.1.1-SNAPSHOT.jar

  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'europe-north1-docker.pkg.dev/artifact-registry-14da/ssb-docker/ssb/statistikktjenester/automation/dapla-dlp-pseudo', 
           '.']
    
  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'europe-north1-docker.pkg.dev/artifact-registry-14da/ssb-docker/ssb/statistikktjenester/automation/dapla-dlp-pseudo']

options:
  logging: CLOUD_LOGGING_ONLY
