micronaut:
  application:
    name: pseudo-service
  server:
    thread-selection: AUTO
    max-request-size: 2gb
#    maxRequestSize: 2gb
    multipart:
      max-file-size: 2gb
#      maxFileSize: 103857
#    max-request-size: 2gb

pseudo.secrets:
    repo:
      secret1:
        content: C5sn7B4YtwcilAwuVx6NuAsMWLusOSA/ldia40ZugDI=
        type: AES256
