micronaut:
  netty:
    event-loops:
      other:
        num-threads: 10
        prefer-native-transport: true
  http:
    client:
      event-loop-group: other
      read-timeout: 120s
    services:
      sid-service:
        url: 'http://localhost:10210'
        path: '/local-sid'

