micronaut:
  application:
    name: dapla-pseudo-service
  server:
    port: 10210
    cors.enabled: true
  thread-selection: AUTO
  max-request-size: 2gb
  multipart:
    max-file-size: 2gb
  caches:
    secrets:
      expire-after-access: 15m
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /api-docs/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /api-docs/swagger-ui/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /api-docs/rapidoc/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /api-docs/redoc/**
endpoints:
  prometheus:
    sensitive: false
  info:
    enabled: true
    sensitive: false
logger:
  levels:
    io.micronaut.security: INFO
    no.ssb.dlp.pseudo.service: DEBUG
