micronaut:
  security:
    token:
      propagation:
        enabled: true
        service-id-regex: "sid-service"

  http:
    services:
      sid-service:
        url: 'http://localhost:10210'
        path: '/local-sid'

