micronaut:
  http:
    services:
      cloud-identity-service:
        url: 'https://cloudidentity.googleapis.com'
        path: '/v1'
        read-timeout: 60s

  caches:
    cloud-identity-service-cache:
      expire-after-write: 30s

gcp:
  http:
    client:
      filter:
        services:
          cloud-identity-service:
            audience: "https://www.googleapis.com/auth/cloud-identity.groups.readonly"

        credentials-path: private/gcp/sa-keys/dev-dapla-pseudo-service-test-sa-key.json