POST {{base_url}}/local-sid/sid/map
Content-Type: application/json
Authorization: Bearer {{keycloak_token}}

{
  "fnr": "11854898347"
}

### Get SID for fnr

GET {{base_url}}/sid/fnr/11854898347?snapshot=423243224
Content-Type: application/json
Authorization: Bearer {{keycloak_token}}

### Get SID for fnr

GET {{base_url}}/sid/fnr/01839899544
Content-Type: application/json
Authorization: Bearer {{keycloak_token}}


### Get SID for snr

GET {{base_url}}/sid/snr/0001ha3
Content-Type: application/json
Authorization: Bearer {{keycloak_token}}


### Pseudonymize using SID mapping

POST {{base_url}}/pseudonymize/file
Content-Type: multipart/form-data; boundary=separator
Authorization: Bearer {{keycloak_token}}

--separator
Content-Disposition: form-data; name="request"
Content-Type: application/json

{
  "targetContentType": "application/json",
  "pseudoConfig": {
    "rules": [
      {
        "name": "fnr",
        "pattern": "**/fnr",
        "func": "map-sid(keyId=papis-key-1)"
      }
    ]
  }
}
--separator
Content-Disposition: form-data; name="data"; filename="data.json"
Content-Type: application/json

< ../../src/test/resources/data/person_3_sid.json
--separator--

### Pseudonymize field usin SID mapping

POST {{base_url}}/pseudonymize/field/sid
Content-Type: application/json
Authorization: Bearer {{keycloak_token}}

{
  "request": {
    "name": "fnr",
    "value": "09898597080"
  }
}

### Pseudonymize field using SID mapping

POST {{base_url}}/pseudonymize/field/sid
Content-Type: application/json
Authorization: Bearer {{keycloak_token}}

{
  "request": {
    "name" : "name",
    "value": "09898597080"
  }
}


### Depseudonymize using SID mapping

POST {{base_url}}/depseudonymize/file
Content-Type: multipart/form-data; boundary=separator
Authorization: Bearer {{keycloak_token}}

--separator
Content-Disposition: form-data; name="request"
Content-Type: application/json

{
  "targetContentType": "application/json",
  "pseudoConfig": {
    "rules": [
      {
        "name": "fnr",
        "pattern": "**/fnr",
        "func": "map-sid(keyId=papis-key-1)"
      }
    ]
  }
}
--separator
Content-Disposition: form-data; name="data"; filename="data.json"
Content-Type: application/json

< ../../src/test/resources/data/person_3_sid_deid.json
--separator--

