### Pseudonymize json file

POST {{base_url}}/pseudonymize/file
Content-Type: multipart/form-data; boundary=separator
Authorization: Bearer {{keycloak_token}}

--separator
Content-Disposition: form-data; name="request"
Content-Type: application/json

{
  "targetContentType": "application/json",
  "pseudoConfig": {
    "rules": [
      {
        "name": "allthenumbers",
        "pattern": "**/*nummer",
        "func": "fpe-digits(keyId=testsecret1)"
      },
      {
        "name": "navn",
        "pattern": "**/navn",
        "func": "fpe-anychar(keyId=testsecret1)"
      }
    ]
  }
}
--separator
Content-Disposition: form-data; name="data"; filename="data.json"
Content-Type: application/json

< ../../src/test/resources/data/15k.json
--separator--

### Pseudonymize zipped archive with multiple json files. Return csv file.

POST {{base_url}}/pseudonymize/file
Content-Type: multipart/form-data; boundary=separator
Authorization: Bearer {{keycloak_token}}

--separator
Content-Disposition: form-data; name="request"
Content-Type: application/json

{
  "targetContentType": "text/csv",
  "pseudoConfig": {
    "rules": [
      {
        "name": "allthenumbers",
        "pattern": "**/*nummer",
        "func": "fpe-digits(keyId=testsecret1)"
      },
      {
        "name": "navn",
        "pattern": "**/navn",
        "func": "fpe-alphanumeric(keyId=testsecret1)"
      }
    ]
  }
}
--separator
Content-Disposition: form-data; name="data"; filename="data.zip"
Content-Type: application/zip

< ../../src/test/resources/data/multiple-json-files.zip
--separator--

