
### Pseudonymize field using DEAD with default keyset

POST {{base_url}}/pseudonymize/field
Content-Type: application/json
Authorization: Bearer {{keycloak_token}}

{
  "request": {
    "name": "fnr",
    "values": [
      "11854898347",
      "01839899544",
      "16910599481",
      "03874398925"
    ]
  }
}

### Pseudonymize field using DEAD with ssb-common-key-2

POST {{base_url}}/pseudonymize/field
Content-Type: application/json
Authorization: Bearer {{keycloak_token}}

{
  "request": {
    "name": "fnr",
    "values": [
      "11854898347",
      "01839899544",
      "16910599481",
      "03874398925"
    ],
    "pseudoFunc": "daead(keyId=ssb-common-key-2)"
  }
}

### Pseudonymize field using DEAD and custom keyset

POST {{base_url}}/pseudonymize/field
Content-Type: application/json
Authorization: Bearer {{keycloak_token}}

{
  "request": {
    "name": "fnr",
    "pattern": "/fnr",
    "values": [
      "11854898347",
      "01839899544",
      "16910599481",
      "03874398925"
    ],
    "pseudoFunc": "daead(keyId=1403797237)",
    "keyset": {
      "kekUri": "gcp-kms://projects/dev-sirius/locations/europe-north1/keyRings/pseudo-service-common-keyring/cryptoKeys/pseudo-service-common-kek-1",
      "encryptedKeyset": "CiQAp91NBuNVCGWtVTE2FAhoRcbbcp+uXgolonL0ojTstS/UKcMStwEAZ30rtXO/8lcBShpbcZ9/pouaX3tgJNxZiy1U1cykPrhhqzpFzCAsrJJNkzwgniqGDOLq+9KzOkj7xoP2V7xKBco/ySzyl0gCpnovBRLCUgq5OMNh/rpKqIr7lMVZfsCVLNPupacSaLoPM+F5DMijAkk7NDTBGwkrRNO34Ev0Kkv/drt+G4DUfdBKLe2QUrEUE0vVfsBw+EZzTC8G3CYemYXC5GYdpTglk0oFDMDs25lBL65SfVQ=",
      "keysetInfo": {
        "primaryKeyId": 1403797237,
        "keyInfo": [
          {
            "typeUrl": "type.googleapis.com/google.crypto.tink.AesSivKey",
            "status": "ENABLED",
            "keyId": 1403797237,
            "outputPrefixType": "TINK"
          }
        ]
      }
    }
  }
}

### Map field to SID and pseudonymize SID values

POST {{base_url}}/pseudonymize/field
Content-Type: application/json
Authorization: Bearer {{keycloak_token}}

{
  "request": {
    "name": "fnr",
    "values": [
      "11854898347",
      "01839899544",
      "16910599481",
      "03874398925"
    ],
    "pseudoFunc": "map-sid(keyId=papis-key-1)"
  }
}

### Null value: DEAD with default keyset
POST {{base_url}}/pseudonymize/field
Content-Type: application/json
Authorization: Bearer {{keycloak_token}}

{
  "request": {
    "name": "empty",
    "values": [
      "20859374701",
      null
    ]
  }
}

### Null value: Map field to SID and pseudonymize SID values
POST {{base_url}}/pseudonymize/field
Content-Type: application/json
Authorization: Bearer {{keycloak_token}}

{
  "request": {
    "name": "fnr",
    "values": [
      "20859374701",
      null
    ],
    "pseudoFunc": "map-sid(keyId=papis-key-1)"
  }
}

