### Pseudonymize using FF31 - person

POST {{base_url}}/pseudonymize/file
Content-Type: multipart/form-data; boundary=separator
Authorization: Bearer {{keycloak_token}}

--separator
Content-Disposition: form-data; name="request"
Content-Type: application/json

{
  "targetContentType": "application/json",
  "pseudoConfig": {
    "keysets": [
  {
    "kekUri": "gcp-kms://projects/dev-sirius/locations/europe-north1/keyRings/pseudo-service-common-keyring/cryptoKeys/pseudo-service-common-kek-1",
    "encryptedKeyset": "CiQAp91NBoOuySeWj+YsdJ0fNxcKDEM0sxBCp2hn8W51EEhiv4oS2AEAZ30rtZdU07cu+QIV7KIKPfMI9KCD7HnW6L6QJtEEyG9vscmHE7xkmWQvANVHhfY+EyDYqwJYdbElAZIwSjsQfgJ0sg82HXz6bs/+g0UMyY40IS6TweKc3Y1+0SMyKQzcz/edmbmXB81Dp/oG6Py9UbNoFzleuhTWBJgoXMsY0l63rJmy7wgEYFX+84r6IGShkcDokb7hx9IfUDrfGfenPi5WOg2yVmnxWETVO2AcrxsKb8/0ywAUbCcTUWFZ0/rS1Dai7bnCke1hMIB0sU1UHV5PeYrp7ds=",
    "keysetInfo": {
    "primaryKeyId": 640864057,
    "keyInfo": [
      {
        "typeUrl": "type.googleapis.com/ssb.crypto.tink.FpeFfxKey",
        "status": "ENABLED",
        "keyId": 640864057,
        "outputPrefixType": "RAW"
      }
    ]
  }
}
    ],
    "rules": [
      {
        "pattern": "**/{fnr}",
        "func": "ff31(keyId=640864057, strategy=skip)"
      },
      {
        "pattern": "**/{fornavn,etternavn}",
        "func": "daead(keyId=ssb-common-key-1)"
      }
    ]
  }
}
--separator
Content-Disposition: form-data; name="data"; filename="data.json"
Content-Type: application/json

< ../../src/test/resources/data/person_3.json
--separator--
