### Pseudonymize 1 000 000 records (zipped) using DAEAD

POST {{base_url}}/pseudonymize/file
Content-Type: multipart/form-data; boundary=separator
Authorization: Bearer {{keycloak_token}}

--separator
Content-Disposition: form-data; name="request"
Content-Type: application/json

{
  "targetContentType": "application/json",
  "pseudoConfig": {
    "keysets": [
{
  "kekUri": "gcp-kms://projects/dev-sirius/locations/europe-north1/keyRings/pseudo-service-common-keyring/cryptoKeys/pseudo-service-common-kek-1",
  "encryptedKeyset": "CiQAp91NBuNVCGWtVTE2FAhoRcbbcp+uXgolonL0ojTstS/UKcMStwEAZ30rtXO/8lcBShpbcZ9/pouaX3tgJNxZiy1U1cykPrhhqzpFzCAsrJJNkzwgniqGDOLq+9KzOkj7xoP2V7xKBco/ySzyl0gCpnovBRLCUgq5OMNh/rpKqIr7lMVZfsCVLNPupacSaLoPM+F5DMijAkk7NDTBGwkrRNO34Ev0Kkv/drt+G4DUfdBKLe2QUrEUE0vVfsBw+EZzTC8G3CYemYXC5GYdpTglk0oFDMDs25lBL65SfVQ=",
  "keysetInfo": {
    "primaryKeyId": 1403797237,
    "keyInfo": [
      {
        "typeUrl": "type.googleapis.com/google.crypto.tink.AesSivKey",
        "status": "ENABLED",
        "keyId": 1403797237,
        "outputPrefixType": "TINK"
      }
    ]
  }
}
    ],
    "rules": [
      {
        "name": "fnr",
        "pattern": "**/foedselsnummer",
        "func": "daead(keyId=1403797237)"
      }
    ]
  }
}
--separator
Content-Disposition: form-data; name="data"; filename="data.zip"
Content-Type: application/zip

< ../../src/test/resources/data/kontaktopplysninger_1000000.json.zip
--separator--


### Pseudonymize using DAEAD

POST {{base_url}}/pseudonymize/file
Content-Type: multipart/form-data; boundary=separator
Authorization: Bearer {{keycloak_token}}

--separator
Content-Disposition: form-data; name="request"
Content-Type: application/json

{
  "targetContentType": "application/json",
  "pseudoConfig": {
    "keysets": [
{
  "kekUri": "gcp-kms://projects/dev-sirius/locations/europe-north1/keyRings/pseudo-service-common-keyring/cryptoKeys/pseudo-service-common-kek-1",
  "encryptedKeyset": "CiQAp91NBuNVCGWtVTE2FAhoRcbbcp+uXgolonL0ojTstS/UKcMStwEAZ30rtXO/8lcBShpbcZ9/pouaX3tgJNxZiy1U1cykPrhhqzpFzCAsrJJNkzwgniqGDOLq+9KzOkj7xoP2V7xKBco/ySzyl0gCpnovBRLCUgq5OMNh/rpKqIr7lMVZfsCVLNPupacSaLoPM+F5DMijAkk7NDTBGwkrRNO34Ev0Kkv/drt+G4DUfdBKLe2QUrEUE0vVfsBw+EZzTC8G3CYemYXC5GYdpTglk0oFDMDs25lBL65SfVQ=",
  "keysetInfo": {
    "primaryKeyId": 1403797237,
    "keyInfo": [
      {
        "typeUrl": "type.googleapis.com/google.crypto.tink.AesSivKey",
        "status": "ENABLED",
        "keyId": 1403797237,
        "outputPrefixType": "TINK"
      }
    ]
  }
}
    ],
    "rules": [
      {
        "name": "navn",
        "pattern": "**/navn",
        "func": "daead(keyId=1403797237)"
      }
    ]
  }
}
--separator
Content-Disposition: form-data; name="data"; filename="data.json"
Content-Type: application/json

< ../../src/test/resources/data/somedata.json
--separator--


### Depseudonymize using DAEAD

POST {{base_url}}/depseudonymize/file
Content-Type: multipart/form-data; boundary=separator
Authorization: Bearer {{keycloak_token}}

--separator
Content-Disposition: form-data; name="request"
Content-Type: application/json

{
  "targetContentType": "application/json",
  "pseudoConfig": {
    "keysets": [
{
  "kekUri": "gcp-kms://projects/dev-sirius/locations/europe-north1/keyRings/pseudo-service-common-keyring/cryptoKeys/pseudo-service-common-kek-1",
  "encryptedKeyset": "CiQAp91NBuNVCGWtVTE2FAhoRcbbcp+uXgolonL0ojTstS/UKcMStwEAZ30rtXO/8lcBShpbcZ9/pouaX3tgJNxZiy1U1cykPrhhqzpFzCAsrJJNkzwgniqGDOLq+9KzOkj7xoP2V7xKBco/ySzyl0gCpnovBRLCUgq5OMNh/rpKqIr7lMVZfsCVLNPupacSaLoPM+F5DMijAkk7NDTBGwkrRNO34Ev0Kkv/drt+G4DUfdBKLe2QUrEUE0vVfsBw+EZzTC8G3CYemYXC5GYdpTglk0oFDMDs25lBL65SfVQ=",
  "keysetInfo": {
    "primaryKeyId": 1403797237,
    "keyInfo": [
      {
        "typeUrl": "type.googleapis.com/google.crypto.tink.AesSivKey",
        "status": "ENABLED",
        "keyId": 1403797237,
        "outputPrefixType": "TINK"
      }
    ]
  }
}
    ],
    "rules": [
      {
        "name": "navn",
        "pattern": "**/navn",
        "func": "daead(keyId=1403797237)"
      }
    ]
  }
}
--separator
Content-Disposition: form-data; name="data"; filename="data.json"
Content-Type: application/json

< ../../src/test/resources/data/somedata-daead-encrypted.json

--separator--


### Pseudonymize using DAEAD - person

POST {{base_url}}/pseudonymize/file
Content-Type: multipart/form-data; boundary=separator
Authorization: Bearer {{keycloak_token}}

--separator
Content-Disposition: form-data; name="request"
Content-Type: application/json

{
  "targetContentType": "application/json",
  "pseudoConfig": {
    "keysets": [
{
  "kekUri": "gcp-kms://projects/dev-sirius/locations/europe-north1/keyRings/pseudo-service-common-keyring/cryptoKeys/pseudo-service-common-kek-1",
  "encryptedKeyset": "CiQAp91NBuNVCGWtVTE2FAhoRcbbcp+uXgolonL0ojTstS/UKcMStwEAZ30rtXO/8lcBShpbcZ9/pouaX3tgJNxZiy1U1cykPrhhqzpFzCAsrJJNkzwgniqGDOLq+9KzOkj7xoP2V7xKBco/ySzyl0gCpnovBRLCUgq5OMNh/rpKqIr7lMVZfsCVLNPupacSaLoPM+F5DMijAkk7NDTBGwkrRNO34Ev0Kkv/drt+G4DUfdBKLe2QUrEUE0vVfsBw+EZzTC8G3CYemYXC5GYdpTglk0oFDMDs25lBL65SfVQ=",
  "keysetInfo": {
    "primaryKeyId": 1403797237,
    "keyInfo": [
      {
        "typeUrl": "type.googleapis.com/google.crypto.tink.AesSivKey",
        "status": "ENABLED",
        "keyId": 1403797237,
        "outputPrefixType": "TINK"
      }
    ]
  }
}
    ],
    "rules": [
      {
        "pattern": "**/{fnr,fornavn,etternavn}",
        "func": "daead(keyId=1403797237)"
      }
    ]
  }
}
--separator
Content-Disposition: form-data; name="data"; filename="data.json"
Content-Type: application/json

< ../../src/test/resources/data/person_3.json
--separator--


### Pseudonymize using DAEAD - kontaktopplysninger

POST {{base_url}}/pseudonymize/file
Content-Type: multipart/form-data; boundary=separator
Authorization: Bearer {{keycloak_token}}

--separator
Content-Disposition: form-data; name="request"
Content-Type: application/json

{
  "targetContentType": "application/json",
  "pseudoConfig": {
    "keysets": [
{
  "kekUri": "gcp-kms://projects/dev-sirius/locations/europe-north1/keyRings/pseudo-service-common-keyring/cryptoKeys/pseudo-service-common-kek-1",
  "encryptedKeyset": "CiQAp91NBuNVCGWtVTE2FAhoRcbbcp+uXgolonL0ojTstS/UKcMStwEAZ30rtXO/8lcBShpbcZ9/pouaX3tgJNxZiy1U1cykPrhhqzpFzCAsrJJNkzwgniqGDOLq+9KzOkj7xoP2V7xKBco/ySzyl0gCpnovBRLCUgq5OMNh/rpKqIr7lMVZfsCVLNPupacSaLoPM+F5DMijAkk7NDTBGwkrRNO34Ev0Kkv/drt+G4DUfdBKLe2QUrEUE0vVfsBw+EZzTC8G3CYemYXC5GYdpTglk0oFDMDs25lBL65SfVQ=",
  "keysetInfo": {
    "primaryKeyId": 1403797237,
    "keyInfo": [
      {
        "typeUrl": "type.googleapis.com/google.crypto.tink.AesSivKey",
        "status": "ENABLED",
        "keyId": 1403797237,
        "outputPrefixType": "TINK"
      }
    ]
  }
}
    ],
    "rules": [
      {
        "pattern": "/{foedselsnummer,gateadresse,telefonnummer}",
        "func": "daead(keyId=1403797237)"
      },
      {
        "pattern": "/email",
        "func": "redact(placeholder=***)"
      }
    ]
  }
}
--separator
Content-Disposition: form-data; name="data"; filename="data.json"
Content-Type: application/json

< ../../src/test/resources/data/kontaktopplysninger_3.json
--separator--


### Repseudonymize using DAEAD - kontaktopplysninger

POST {{base_url}}/repseudonymize/file
Content-Type: multipart/form-data; boundary=separator
Authorization: Bearer {{keycloak_token}}

--separator
Content-Disposition: form-data; name="request"
Content-Type: application/json

{
  "targetContentType": "application/json",
  "sourcePseudoConfig": {
    "keysets": [
{
  "kekUri": "gcp-kms://projects/dev-sirius/locations/europe-north1/keyRings/pseudo-service-common-keyring/cryptoKeys/pseudo-service-common-kek-1",
  "encryptedKeyset": "CiQAp91NBuNVCGWtVTE2FAhoRcbbcp+uXgolonL0ojTstS/UKcMStwEAZ30rtXO/8lcBShpbcZ9/pouaX3tgJNxZiy1U1cykPrhhqzpFzCAsrJJNkzwgniqGDOLq+9KzOkj7xoP2V7xKBco/ySzyl0gCpnovBRLCUgq5OMNh/rpKqIr7lMVZfsCVLNPupacSaLoPM+F5DMijAkk7NDTBGwkrRNO34Ev0Kkv/drt+G4DUfdBKLe2QUrEUE0vVfsBw+EZzTC8G3CYemYXC5GYdpTglk0oFDMDs25lBL65SfVQ=",
  "keysetInfo": {
    "primaryKeyId": 1403797237,
    "keyInfo": [
      {
        "typeUrl": "type.googleapis.com/google.crypto.tink.AesSivKey",
        "status": "ENABLED",
        "keyId": 1403797237,
        "outputPrefixType": "TINK"
      }
    ]
  }
}
    ],
    "rules": [
      {
        "name": "rule-1",
        "pattern": "**/{foedselsnummer,gateadresse,telefonnummer}",
        "func": "daead(keyId=1403797237)"
      }
    ]
  },
  "targetPseudoConfig": {
    "keysets": [
{
  "kekUri": "gcp-kms://projects/dev-sirius/locations/europe-north1/keyRings/pseudo-service-common-keyring/cryptoKeys/pseudo-service-common-kek-1",
  "encryptedKeyset": "CiQAp91NBn/O1GqfVvpNwLrDTTocNzhieGklCwrY57Zub+yvV9YStQEAZ30rtXy4WuEfBZMgKhuSbbcqqbnfuXoSAqpQXBcy+d8z9k7V9/xag6/sUCP/+e2NVd7PIumpFXqnRdBUw3YbSTITbGiP05MdE0cSyX+XvI41yTLa/bHddQojX7D2ls9Pei8+T6ZCAbtmPwrkyMbxWahU60A2HNmq2qvCmM5Hyaej6EHSf007nbxch004Uwi1FpI/6Am0Z9M7uJ+hRVF0YIv1nEf0lmoXiJDfC4GGDh+BbGBJ",
  "keysetInfo": {
    "primaryKeyId": 208741162,
    "keyInfo": [
      {
        "typeUrl": "type.googleapis.com/google.crypto.tink.AesSivKey",
        "status": "ENABLED",
        "keyId": 208741162,
        "outputPrefixType": "TINK"
      }
    ]
  }
}
    ],
    "rules": [
      {
        "name": "rule-1",
        "pattern": "**/{foedselsnummer,gateadresse,telefonnummer,email}",
        "func": "daead(keyId=208741162)"
      }
    ]
  }
}

--separator
Content-Disposition: form-data; name="data"; filename="data.json"
Content-Type: application/json

< ../../src/test/resources/data/kontaktopplysninger_3-deid.json
--separator--

### Pseudonymize using DAEAD and default key - person

POST {{base_url}}/pseudonymize/file
Content-Type: multipart/form-data; boundary=separator
Authorization: Bearer {{keycloak_token}}

--separator
Content-Disposition: form-data; name="request"
Content-Type: application/json

{
  "targetContentType": "application/json",
  "pseudoConfig": {
    "rules": [
      {
        "pattern": "**/{fnr,fornavn,etternavn}",
        "func": "daead(keyId=ssb-common-key-1)"
      }
    ]
  }
}
--separator
Content-Disposition: form-data; name="data"; filename="data.json"
Content-Type: application/json

< ../../src/test/resources/data/person_3.json
--separator--


