POST {{base_url}}/local-sid/sid/map
Content-Type: application/json
Authorization: Bearer {{keycloak_token}}

{
  "fnr": "16510599481"
}

###
POST {{base_url}}/local-sid/sid/map
Content-Type: application/json
Authorization: Bearer {{keycloak_token}}

{
  "snr": "0001ha3"
}

### Get SID for fnr

GET {{base_url}}/sid/fnr/11854898347?snapshot=423243224
Content-Type: application/json
Authorization: Bearer {{keycloak_token}}

### Get SID for fnr

GET {{base_url}}/sid/fnr/08896298179
Content-Type: application/json
Authorization: Bearer {{keycloak_token}}


### Get SID for snr

GET {{base_url}}/sid/snr/0001ha3
Content-Type: application/json
Authorization: Bearer {{keycloak_token}}

### Map batch of fnrs

POST {{base_url}}/sid/map/batch
Content-Type: application/json
Authorization: Bearer {{keycloak_token}}

{
  "fnrList": [
    "11854898347",
    "01839899544",
    "16910599481",
    "03874398920"
  ]
}

### Map batch of snrs

POST {{base_url}}/sid/map/batch
Content-Type: application/json
Authorization: Bearer {{keycloak_token}}

{
  "snrList": [
    "0001ha3",
    "0006kh2"
  ]
}


### Look up SID for a list of FNRs and return those that are not found

POST {{base_url}}/sid/lookup/batch
Content-Type: application/json
Authorization: Bearer {{keycloak_token}}

{
  "fnrList": [
    "11854898347",
    "01839899544",
    "16910599481",
    "03874398920"
  ]
}

### Pseudonymize using SID mapping

POST {{base_url}}/pseudonymize/file
Content-Type: multipart/form-data; boundary=separator
X-Correlation-Id: ad94e671-7388-4fa2-8b0a-f9f3ec970d9b
Authorization: Bearer {{keycloak_token}}

--separator
Content-Disposition: form-data; name="request"
Content-Type: application/json

{
  "targetContentType": "application/json",
  "pseudoConfig": {
    "rules": [
      {
        "name": "fnr",
        "pattern": "**/fnr",
        "func": "map-sid(keyId=papis-key-1,snapshotDate=2023-07-05)"
      }
    ]
  }
}
--separator
Content-Disposition: form-data; name="data"; filename="data.json"
Content-Type: application/json

< ../../src/test/resources/data/person_3_sid.json
--separator--

### Depseudonymize using SID mapping

POST {{base_url}}/depseudonymize/file
Content-Type: multipart/form-data; boundary=separator
Authorization: Bearer {{keycloak_token}}

--separator
Content-Disposition: form-data; name="request"
Content-Type: application/json

{
  "targetContentType": "application/json",
  "pseudoConfig": {
    "rules": [
      {
        "name": "fnr",
        "pattern": "**/fnr",
        "func": "map-sid(keyId=papis-key-1)"
      }
    ]
  }
}
--separator
Content-Disposition: form-data; name="data"; filename="data.json"
Content-Type: application/json

< ../../src/test/resources/data/person_3_sid_deid.json
--separator--

### Null value: Map to SID and pseudonymize SID values with papis-key
POST {{base_url}}/pseudonymize/file
Content-Type: multipart/form-data; boundary=separator
Authorization: Bearer {{keycloak_token}}

--separator
Content-Disposition: form-data; name="request"
Content-Type: application/json

{
  "targetContentType": "application/json",
  "pseudoConfig": {
    "rules": [
      {
        "pattern": "**/{fnr}",
        "func": "map-sid(keyId=papis-key-1)"
      }
    ]
  }
}
--separator
Content-Disposition: form-data; name="data"; filename="null_fnr.json"
Content-Type: application/json

< ../../src/test/resources/data/null_fnr.json
--separator--